# #####################################################################################################################
# LICENSE
# #####################################################################################################################

#
# This file is part of devcontainer.
#
# The devcontainer is free software: you can redistribute it and/or modify it under the terms of the GNU Affero
# General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# The devcontainer is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along with devcontainer. If not, see
# <https://www.gnu.org/licenses/>.
#

# #####################################################################################################################
# PRELUDE
# #####################################################################################################################

#
# HADOLINT
#

# This is a container intended to be used to run tests which might require elevated permissions
# hadolint global ignore=DL3002

#
# PRE-ARGUMENTS
#

ARG PROJECT_NAME
ARG PROJECT_VERSION

# ---------------------------------------------------------------------------------------------------------------------
# BASE IMAGE
# ---------------------------------------------------------------------------------------------------------------------

FROM ${PROJECT_NAME}:${PROJECT_VERSION}

# ---------------------------------------------------------------------------------------------------------------------
# ARGUMENTS
# ---------------------------------------------------------------------------------------------------------------------

#
# DOCKER BUILDKIT
#

ARG BUILDARCH
ARG BUILDOS
ARG BUILDPLATFORM
ARG TARGETARCH
ARG TARGETOS
ARG TARGETPLATFORM

# #####################################################################################################################
# SETUP TEST ENVIRONMENT
# #####################################################################################################################

USER root

SHELL [ "/bin/bash", "-o", "pipefail", "-c" ]

# ---------------------------------------------------------------------------------------------------------------------
# INSTALL SYSTEM PACKAGES
# ---------------------------------------------------------------------------------------------------------------------

RUN export DEBIAN_FRONTEND="noninteractive" \
    && apt-get update \
    && apt-get -y install --no-install-recommends \
    bats \
    bats-assert \
    bats-file \
    bats-support \
    && apt-get autoremove -y \
    && apt-get clean autoclean -y \
    && rm -r /var/cache/* /var/lib/apt/lists/*

# ---------------------------------------------------------------------------------------------------------------------
# COPY TEST FILES
# ---------------------------------------------------------------------------------------------------------------------

COPY ./tests/* /tests/

# #####################################################################################################################
# RUN
# #####################################################################################################################

# ---------------------------------------------------------------------------------------------------------------------
# ENTRYPOINT
# ---------------------------------------------------------------------------------------------------------------------

ENTRYPOINT [ "/usr/bin/bats", "/tests/" ]
