name: Lint

on:
  push:
    branches:
      - '**'

env:
  DOCKER_BUILDKIT: 1
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  PROJECT_DOCKER_USER: ${{ vars.PROJECT_DOCKER_USER }}

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Lint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run lint
        run: |
          make lint
