# ######################################################################################################################
# LICENSE
# ######################################################################################################################

#
# This file is part of container-dev-base.
#
# The container-dev-base is free software: you can redistribute it and/or modify it under the terms of the GNU Affero
# General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# The container-dev-base is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along with container-dev-base. If not, see
# <https://www.gnu.org/licenses/>.
#

# ######################################################################################################################
# WORKFLOW
# ######################################################################################################################

# ----------------------------------------------------------------------------------------------------------------------
# METADATA
# ----------------------------------------------------------------------------------------------------------------------

#
# GENERAL
#

name: On Pull Requests

#
# TRIGGER
#

on:
  pull_request:

# ######################################################################################################################
# ENVIRONMENT VARIABLES
# ######################################################################################################################

env:
  DOCKER_BUILDKIT: 1
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}

# ######################################################################################################################
# JOBS
# ######################################################################################################################

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        uses: ./.github/actions/lint

  scan:
    name: Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan
        uses: ./.github/actions/scan

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build
      - name: Test
        uses: ./.github/actions/test
