name: Workflow - On Tags

on:
  push:
    tags:        
      - 'v*'

env:
  DOCKER_BUILDKIT: 1
  PROJECT_DOCKER_PLATFORMS: ${{ vars.PROJECT_DOCKER_PLATFORMS }}
  PROJECT_DOCKER_TEST_ARCH: ${{ vars.PROJECT_DOCKER_TEST_ARCH }}
  PROJECT_DOCKER_REPOSITORY: ${{ vars.PROJECT_DOCKER_REPOSITORY }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Lint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up hadolint
        uses: ./.github/actions/setup-hadolint
      - name: Run lint
        run: |
          make lint

  scan:
    runs-on: ubuntu-22.04
    name: Scan
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up checkov
        uses: ./.github/actions/setup-checkov
      - name: Run scan
        run: |
          make scan

  build:
    runs-on: ubuntu-22.04
    name: Build
    needs:
      - lint
      - scan
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Run build
        run: |
          make build

  test:
    runs-on: ubuntu-22.04
    name: Test
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Set up container-structure-test
        uses: ./.github/actions/setup-container-structure-test
      - name: Run test
        run: |
          make test

  release:
    runs-on: ubuntu-22.04
    name: Release
    needs: test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Run release
        env:
          PROJECT_DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          PROJECT_DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
        run: |
          make release
