# ######################################################################################################################
# LICENSE
# ######################################################################################################################

#
# This file is part of container-dev-base.
#
# The container-dev-base is free software: you can redistribute it and/or modify it under the terms of the GNU Affero
# General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# The container-dev-base is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along with container-dev-base. If not, see
# <https://www.gnu.org/licenses/>.
#

# ######################################################################################################################
# WORKFLOW
# ######################################################################################################################

# ----------------------------------------------------------------------------------------------------------------------
# METADATA
# ----------------------------------------------------------------------------------------------------------------------

#
# GENERAL
#

name: Pipeline

#
# TRIGGER
#

on:
  pull_request:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# ######################################################################################################################
# ENVIRONMENT VARIABLES
# ######################################################################################################################

env:
  DOCKER_BUILDKIT: 1
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}

# ######################################################################################################################
# JOBS
# ######################################################################################################################

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        uses: mundoalem/action-prepare@initial
        with:
          type: container
          job: ci

      - name: Lint
        run: |
          make lint

      - name: Scan
        run: |
          make scan

      - name: Build [amd64]
        env:
          PROJECT_DOCKER_PLATFORMS: linux/amd64
        run: |
          make build

      - name: Build [arm64]
        env:
          PROJECT_DOCKER_PLATFORMS: linux/arm64
        run: |
          make build

      - name: Test [amd64]
        env:
          PROJECT_DOCKER_PLATFORMS: linux/amd64
        run: |
          make test

      - name: Test [arm64]
        env:
          PROJECT_DOCKER_PLATFORMS: linux/arm64
        run: |
          make test
  cd:
    name: CD
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        uses: mundoalem/action-prepare@initial
        with:
          type: container
          job: cd

      - name: Release
        env:
          PROJECT_DOCKER_PLATFORMS: linux/amd64,linux/arm64
        run: |
          make release
